"""
Pydantic models for the User Preference module.

Request:  SaveViewRequest
Domain:   UserPreferenceView
Response: ViewResponse, ViewListResponse

Filter and KPI keys are constrained to known enums so the repository can
safely build SQL array literals without risk of injection.
"""

from __future__ import annotations

from typing import Literal, Optional
from pydantic import BaseModel, Field, field_validator

# --------------------------------------------------------------------------- #
#  Allowed keys — the single source of truth for what can be toggled          #
# --------------------------------------------------------------------------- #

FilterKey = Literal["channel", "category", "retailer", "country"]

KpiKey = Literal[
    "dollar_sales",
    "volume_sales",
    "dollar_share",
    "volume_share",
    "distribution",
    "yoy_growth",
]

# Human-readable labels used when auto-generating the view name
FILTER_LABELS: dict[str, str] = {
    "channel":  "Channel",
    "category": "Category",
    "retailer": "Retailer",
    "country":  "Country",
}

KPI_LABELS: dict[str, str] = {
    "dollar_sales":  "Dollar Sales",
    "volume_sales":  "Volume Sales",
    "dollar_share":  "Dollar Share",
    "volume_share":  "Volume Share",
    "distribution":  "Distribution",
    "yoy_growth":    "YoY Growth",
}


# --------------------------------------------------------------------------- #
#  Request models                                                             #
# --------------------------------------------------------------------------- #

class SaveViewRequest(BaseModel):
    """
    Body for creating or updating a saved view.

    The view name is NOT accepted from the client — it is always
    auto-generated by the service from the visible filters and KPIs.

    Example:
        {
            "visibleFilters": ["channel", "category"],
            "visibleKpis": ["dollar_sales", "yoy_growth"],
            "isDefault": false
        }
    """
    visible_filters: list[FilterKey] = Field(
        alias="visibleFilters",
        default_factory=list,
        description="Filter dimension keys to show on the dashboard.",
    )
    visible_kpis: list[KpiKey] = Field(
        alias="visibleKpis",
        default_factory=list,
        description="KPI card keys to show on the dashboard.",
    )
    is_default: bool = Field(
        alias="isDefault",
        default=False,
        description="If true, this view is auto-applied when the dashboard opens.",
    )

    model_config = {"populate_by_name": True}

    @field_validator("visible_filters", "visible_kpis")
    @classmethod
    def _remove_duplicates(cls, values: list[str]) -> list[str]:
        """
        Remove duplicate keys while preserving first-seen order so the
        generated view name and persisted arrays stay deterministic.
        """
        return list(dict.fromkeys(values))


# --------------------------------------------------------------------------- #
#  Domain / response models                                                   #
# --------------------------------------------------------------------------- #

class UserPreferenceView(BaseModel):
    """
    A single saved dashboard view. Mirrors one row of
    workspace.preferences.user_dashboard_views.
    """
    view_id: str = Field(alias="viewId")
    user_id: str = Field(alias="userId")
    generated_view_name: str = Field(alias="generatedViewName")
    visible_filters: list[str] = Field(alias="visibleFilters")
    visible_kpis: list[str] = Field(alias="visibleKpis")
    is_default: bool = Field(alias="isDefault")
    created_at: Optional[str] = Field(alias="createdAt", default=None)
    updated_at: Optional[str] = Field(alias="updatedAt", default=None)

    model_config = {"populate_by_name": True}


class ViewListResponse(BaseModel):
    """Response envelope for GET /api/preferences/views."""
    views: list[UserPreferenceView]

    model_config = {"populate_by_name": True}
