# Databricks notebook source
# MAGIC %md
# MAGIC # Create User Preferences Table
# MAGIC
# MAGIC **Purpose:** Creates the Delta table that persists per-user dashboard view preferences.
# MAGIC
# MAGIC Each row represents one saved view for one user:
# MAGIC - Which filter dropdowns are visible on the dashboard
# MAGIC - Which KPI cards are visible on the dashboard
# MAGIC - Whether this view is the user's default (loaded automatically on page open)
# MAGIC
# MAGIC **Idempotent:** Safe to run multiple times. Uses `CREATE SCHEMA IF NOT EXISTS`
# MAGIC and `CREATE TABLE IF NOT EXISTS` throughout.

# COMMAND ----------

# =============================================================================
# Configuration — adjust if your catalog or schema names differ
# =============================================================================

CATALOG = "workspace"
SCHEMA  = "preferences"
TABLE   = "user_dashboard_views"

FULL_TABLE = f"{CATALOG}.{SCHEMA}.{TABLE}"

print(f"Target table: {FULL_TABLE}")

# COMMAND ----------
# MAGIC %md
# MAGIC ## Step 1 — Create the schema (if not exists)

# COMMAND ----------

spark.sql(f"CREATE SCHEMA IF NOT EXISTS {CATALOG}.{SCHEMA}")
print(f"Schema ready: {CATALOG}.{SCHEMA}")

# COMMAND ----------
# MAGIC %md
# MAGIC ## Step 2 — Create the Delta table (if not exists)

# COMMAND ----------

spark.sql(f"""
CREATE TABLE IF NOT EXISTS {FULL_TABLE} (

  -- ── Identity ────────────────────────────────────────────────────────────
  user_id   STRING  NOT NULL
    COMMENT 'Email or unique identifier of the user who owns this view.
             Sourced from the X-Forwarded-Email header injected by Databricks Apps.',

  view_id   STRING  NOT NULL
    COMMENT 'UUID of the saved view — generated by the backend on creation.
             Acts as the primary key together with user_id.',

  -- ── View configuration ──────────────────────────────────────────────────
  generated_view_name  STRING
    COMMENT 'Auto-generated human-readable name built from the selected filter
             and KPI names. Example: Channel · Category | Dollar Sales · YoY Growth.
             Never manually entered — always derived by the backend service.',

  visible_filters  ARRAY<STRING>
    COMMENT 'Ordered list of filter dimension keys the user wants visible on the
             dashboard. Possible values: channel, category, retailer, country.
             An empty array means all filters are hidden.',

  visible_kpis  ARRAY<STRING>
    COMMENT 'Ordered list of KPI card keys the user wants visible on the dashboard.
             Possible values: dollar_sales, volume_sales, dollar_share, volume_share,
             distribution, yoy_growth.
             An empty array means all KPI cards are hidden.',

  -- ── Default flag ────────────────────────────────────────────────────────
  is_default  BOOLEAN  NOT NULL
    COMMENT 'When TRUE, this view is automatically applied when the user opens the
             dashboard. At most one row per user_id should have is_default = TRUE.
             The backend always writes this value explicitly (defaults to FALSE
             in the service layer). Enforced on write by the backend service.',

  -- ── Audit ───────────────────────────────────────────────────────────────
  created_at  TIMESTAMP  NOT NULL
    COMMENT 'UTC timestamp when this view was first saved.',

  updated_at  TIMESTAMP  NOT NULL
    COMMENT 'UTC timestamp of the most recent update to this row.'

)
USING DELTA
COMMENT 'Stores per-user dashboard view preferences for the AI Console application.
Each row represents one saved view configuration (visible filters + KPI cards).
Owned by the preferences module; written exclusively via the FastAPI backend.'
TBLPROPERTIES (
  'layer'       = 'application',
  'module'      = 'user-preferences',
  'delta.enableChangeDataFeed' = 'true'
)
""")

print(f"Table ready: {FULL_TABLE}")

# COMMAND ----------
# MAGIC %md
# MAGIC ## Step 3 — Verify table schema

# COMMAND ----------

print(f"Table: {FULL_TABLE}")
display(spark.sql(f"DESCRIBE TABLE EXTENDED {FULL_TABLE}"))

# COMMAND ----------
# MAGIC %md
# MAGIC ## Step 4 — Verify table is empty and queryable

# COMMAND ----------

row_count = spark.sql(f"SELECT COUNT(*) AS row_count FROM {FULL_TABLE}").collect()[0]["row_count"]
print(f"Row count: {row_count} (expected 0 for a fresh table)")

display(spark.sql(f"SELECT * FROM {FULL_TABLE} LIMIT 10"))

# COMMAND ----------
# MAGIC %md
# MAGIC ## Summary
# MAGIC
# MAGIC | Property | Value |
# MAGIC |----------|-------|
# MAGIC | Full table path | `workspace.preferences.user_dashboard_views` |
# MAGIC | Format | Delta |
# MAGIC | Primary key (logical) | `user_id` + `view_id` |
# MAGIC | Default constraint | At most one `is_default = TRUE` per `user_id` (enforced in service layer) |
# MAGIC | Change Data Feed | Enabled (for future audit/streaming use cases) |
# MAGIC
# MAGIC **Next step:** Run the backend preferences service which will INSERT, UPDATE, and
# MAGIC DELETE rows in this table via the Databricks SQL Warehouse connection.
